### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by darkclouder** [darkclouder/rust-chess#1]
- [x] Piece movement
  - [x] Pawn
    - [x] En passant
    - [x] Promotion
  - [x] Knight
  - [x] Bishop
  - [x] Rook
  - [x] Queen
  - [x] King
    - [ ] Castling (what's missing is king is not allowed to be attaceked!)
- [x] Check
  - [x] Don't allow moves that lead to self-check
- [x] Check mate
- [ ] Move history
- [ ] Stalemate
- [ ] Dead position
- [ ] Draw by agreement
- [x] Surrender
- [ ] Threefold repetition
- [ ] New game
- [ ] Add unit tests for obscure combinations
  - [ ] Checkmate only with promotion
- [ ] Code cleanup and refactoring (always possible :P)
